name: daily_wallpapers
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cached_network_image: ^3.4.0
  flutter:
    sdk: flutter
  provider: ^6.1.2
cupertino_icons: ^1.0.6
http: ^0.13.3
cached_network_image: ^3.2.0
provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
